### ISSUE TITLE
Grafana-flowcharting changes not reflected on dashboard while it works in edit mode of the panel

### ISSUE THREAD

**Issue by debasishdas033** [algenty/grafana-flowcharting#205]
I have configured one grafana-flowcharting panel which shows the color change properly based on threshold. Mapping rule works only good when this panel is opened in edit mode. But it does not show the color change on the dashboard view when I save and apply all the changes to show on dashboard.

**Comment by debasishdas033** [comment]
It works on Firefox but not on chrome.

**Comment by algenty** [comment]
ok, need to try

**Comment by debasishdas033** [comment]
It is fixed now. After saving the changes in the panel, the browser should be refreshed to reflect the new changes on the dashboard.
I was not refreshing as I was expecting it will happen automatically.

**Comment by traztor** [comment]
Having the same issue, Mapping rule works only good when this panel is opened in edit mode. Rules won't save in between Apply. Both on Chrome and Firefox.

**Comment by algenty** [comment]
Can you try snapshot version in 
https://algenty.github.io/flowcharting-repository/ARCHIVES.html

**Comment by traztor** [comment]
Tried the snapshot version, now it is working only for metric type series in Firefox. 

Metric Type when set to Table is still not saving on either browsers and not working on dashboard outside of edit mode.

Also, when I set Aggregation for Last and Last (not null) they are both returning nulls. I inspect the data the table data from inspect tab there are no nulls in data table. 

My use case is heavily dependent on Metric Type Table and Last/Last (not null) working correctly.

**Comment by algenty** [comment]
What is your version of grafana ?
I have the bug on grafana v7 not v6

**Comment by traztor** [comment]
Yes I am using the latest Grafana. Are you recommending to downgrade to Grafana v6 or should I wait for a fix in the next release.

**Comment by algenty** [comment]
no,i need to fix it in v7. it's a minor bug

**Comment by algenty** [comment]
I confirm, this bug is a regression in grafana 7.1

**Comment by algenty** [comment]
FI
https://github.com/grafana/grafana/issues/26580

**Comment by lennyoed** [comment]
Is there any current update to this issue?  Is the fix simply to downgrade Grafana to version 6?  Is there a known patch?  Does additional data need to be collected and provided?

**Comment by algenty** [comment]
Fixed at https://algenty.github.io/flowcharting-repository/ARCHIVES.html
Need feedback
